apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::960176666025:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::960176666025:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18RIHKJ1JREYB
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-26T20:56:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1914"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 952e7541-472a-4df3-b9f4-b139ff7ae705
